server:
  port: ${PORT:8080}

logging:
  level:
    org.atmosphere: warn

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.gladtek
  copilot:
    enable: false

